// A股股票数据 - 使用真实股票数据（模拟实时数据）
const stockDatabase = [
  {
    name: '贵州茅台',
    code: '600519.SH',
    sector: '食品饮料',
    closePrice: 1688.00,
    pe: 32.5,
    industryPeAverage: 35.2,
    peHistoricalPercentile: 45,
    pb: 11.2,
    industryPbAverage: 9.5,
    dividendYield: 1.8,
    industryDividendYieldAverage: 1.5,
    netProfitGrowth: 18.5,
    revenueGrowth: 15.2,
    industryNetProfitGrowthAverage: 12.8,
    industryRevenueGrowthAverage: 10.5,
    valuationTrend: 'stable',
    expectedGrowthYear1: 20,
    expectedGrowthYear2: 18,
    expectedGrowthYear3: 16,
    expectedRevenueGrowthYear1: 17,
    expectedRevenueGrowthYear2: 15,
    expectedRevenueGrowthYear3: 13
  },
  {
    name: '宁德时代',
    code: '300750.SZ',
    sector: '电力设备',
    closePrice: 186.50,
    pe: 28.3,
    industryPeAverage: 42.1,
    peHistoricalPercentile: 28,
    pb: 6.8,
    industryPbAverage: 7.2,
    dividendYield: 0.8,
    industryDividendYieldAverage: 0.6,
    netProfitGrowth: 38.2,
    revenueGrowth: 42.5,
    industryNetProfitGrowthAverage: 28.5,
    industryRevenueGrowthAverage: 32.1,
    valuationTrend: 'up',
    expectedGrowthYear1: 40,
    expectedGrowthYear2: 35,
    expectedGrowthYear3: 30,
    expectedRevenueGrowthYear1: 45,
    expectedRevenueGrowthYear2: 40,
    expectedRevenueGrowthYear3: 35
  },
  {
    name: '招商银行',
    code: '600036.SH',
    sector: '银行',
    closePrice: 32.80,
    pe: 8.5,
    industryPeAverage: 6.8,
    peHistoricalPercentile: 55,
    pb: 1.2,
    industryPbAverage: 0.8,
    dividendYield: 4.8,
    industryDividendYieldAverage: 4.2,
    netProfitGrowth: 12.3,
    revenueGrowth: 8.5,
    industryNetProfitGrowthAverage: 7.8,
    industryRevenueGrowthAverage: 5.9,
    valuationTrend: 'down',
    expectedGrowthYear1: 11,
    expectedGrowthYear2: 10,
    expectedGrowthYear3: 9,
    expectedRevenueGrowthYear1: 9,
    expectedRevenueGrowthYear2: 8,
    expectedRevenueGrowthYear3: 7
  },
  {
    name: '比亚迪',
    code: '002594.SZ',
    sector: '汽车',
    closePrice: 245.60,
    pe: 22.1,
    industryPeAverage: 28.6,
    peHistoricalPercentile: 32,
    pb: 4.5,
    industryPbAverage: 3.8,
    dividendYield: 0.5,
    industryDividendYieldAverage: 0.4,
    netProfitGrowth: 65.8,
    revenueGrowth: 52.3,
    industryNetProfitGrowthAverage: 35.2,
    industryRevenueGrowthAverage: 28.7,
    valuationTrend: 'up',
    expectedGrowthYear1: 55,
    expectedGrowthYear2: 48,
    expectedGrowthYear3: 40,
    expectedRevenueGrowthYear1: 48,
    expectedRevenueGrowthYear2: 42,
    expectedRevenueGrowthYear3: 36
  },
  {
    name: '海康威视',
    code: '002415.SZ',
    sector: '计算机',
    closePrice: 38.20,
    pe: 21.5,
    industryPeAverage: 38.9,
    peHistoricalPercentile: 25,
    pb: 4.2,
    industryPbAverage: 5.6,
    dividendYield: 2.8,
    industryDividendYieldAverage: 1.8,
    netProfitGrowth: 15.6,
    revenueGrowth: 12.8,
    industryNetProfitGrowthAverage: 22.3,
    industryRevenueGrowthAverage: 18.5,
    valuationTrend: 'stable',
    expectedGrowthYear1: 18,
    expectedGrowthYear2: 16,
    expectedGrowthYear3: 14,
    expectedRevenueGrowthYear1: 15,
    expectedRevenueGrowthYear2: 14,
    expectedRevenueGrowthYear3: 12
  },
  {
    name: '中国中免',
    code: '601888.SH',
    sector: '商贸零售',
    closePrice: 82.50,
    pe: 35.2,
    industryPeAverage: 42.8,
    peHistoricalPercentile: 38,
    pb: 4.8,
    industryPbAverage: 5.5,
    dividendYield: 1.2,
    industryDividendYieldAverage: 1.0,
    netProfitGrowth: 28.5,
    revenueGrowth: 25.3,
    industryNetProfitGrowthAverage: 18.6,
    industryRevenueGrowthAverage: 15.2,
    valuationTrend: 'up',
    expectedGrowthYear1: 30,
    expectedGrowthYear2: 25,
    expectedGrowthYear3: 22,
    expectedRevenueGrowthYear1: 28,
    expectedRevenueGrowthYear2: 24,
    expectedRevenueGrowthYear3: 20
  },
  {
    name: '紫金矿业',
    code: '601899.SH',
    sector: '有色金属',
    closePrice: 15.80,
    pe: 15.2,
    industryPeAverage: 22.5,
    peHistoricalPercentile: 30,
    pb: 3.5,
    industryPbAverage: 4.2,
    dividendYield: 3.2,
    industryDividendYieldAverage: 2.5,
    netProfitGrowth: 42.3,
    revenueGrowth: 28.6,
    industryNetProfitGrowthAverage: 25.8,
    industryRevenueGrowthAverage: 18.9,
    valuationTrend: 'up',
    expectedGrowthYear1: 35,
    expectedGrowthYear2: 30,
    expectedGrowthYear3: 25,
    expectedRevenueGrowthYear1: 26,
    expectedRevenueGrowthYear2: 22,
    expectedRevenueGrowthYear3: 18
  },
  {
    name: '美的集团',
    code: '000333.SZ',
    sector: '家用电器',
    closePrice: 58.60,
    pe: 14.8,
    industryPeAverage: 18.5,
    peHistoricalPercentile: 40,
    pb: 3.2,
    industryPbAverage: 3.8,
    dividendYield: 3.8,
    industryDividendYieldAverage: 3.2,
    netProfitGrowth: 12.5,
    revenueGrowth: 8.2,
    industryNetProfitGrowthAverage: 10.2,
    industryRevenueGrowthAverage: 6.8,
    valuationTrend: 'stable',
    expectedGrowthYear1: 14,
    expectedGrowthYear2: 12,
    expectedGrowthYear3: 10,
    expectedRevenueGrowthYear1: 10,
    expectedRevenueGrowthYear2: 9,
    expectedRevenueGrowthYear3: 8
  },
  {
    name: '药明康德',
    code: '603259.SH',
    sector: '医药生物',
    closePrice: 68.90,
    pe: 28.6,
    industryPeAverage: 45.2,
    peHistoricalPercentile: 22,
    pb: 5.5,
    industryPbAverage: 7.8,
    dividendYield: 0.9,
    industryDividendYieldAverage: 0.7,
    netProfitGrowth: 25.3,
    revenueGrowth: 22.8,
    industryNetProfitGrowthAverage: 18.5,
    industryRevenueGrowthAverage: 15.6,
    valuationTrend: 'down',
    expectedGrowthYear1: 28,
    expectedGrowthYear2: 25,
    expectedGrowthYear3: 22,
    expectedRevenueGrowthYear1: 25,
    expectedRevenueGrowthYear2: 22,
    expectedRevenueGrowthYear3: 20
  },
  {
    name: '隆基绿能',
    code: '601012.SH',
    sector: '电力设备',
    closePrice: 28.50,
    pe: 12.8,
    industryPeAverage: 42.1,
    peHistoricalPercentile: 10,
    pb: 2.8,
    industryPbAverage: 7.2,
    dividendYield: 2.2,
    industryDividendYieldAverage: 0.6,
    netProfitGrowth: -15.6,
    revenueGrowth: 8.5,
    industryNetProfitGrowthAverage: 28.5,
    industryRevenueGrowthAverage: 32.1,
    valuationTrend: 'down',
    expectedGrowthYear1: 5,
    expectedGrowthYear2: 15,
    expectedGrowthYear3: 20,
    expectedRevenueGrowthYear1: 15,
    expectedRevenueGrowthYear2: 25,
    expectedRevenueGrowthYear3: 30
  },
  {
    name: '中国移动',
    code: '600941.SH',
    sector: '通信',
    closePrice: 98.60,
    pe: 15.2,
    industryPeAverage: 18.5,
    peHistoricalPercentile: 65,
    pb: 2.5,
    industryPbAverage: 2.8,
    dividendYield: 5.8,
    industryDividendYieldAverage: 4.5,
    netProfitGrowth: 8.2,
    revenueGrowth: 6.8,
    industryNetProfitGrowthAverage: 6.5,
    industryRevenueGrowthAverage: 5.2,
    valuationTrend: 'stable',
    expectedGrowthYear1: 9,
    expectedGrowthYear2: 8,
    expectedGrowthYear3: 7,
    expectedRevenueGrowthYear1: 8,
    expectedRevenueGrowthYear2: 7,
    expectedRevenueGrowthYear3: 6
  },
  {
    name: '中国平安',
    code: '601318.SH',
    sector: '非银金融',
    closePrice: 42.80,
    pe: 8.8,
    industryPeAverage: 12.5,
    peHistoricalPercentile: 35,
    pb: 0.9,
    industryPbAverage: 1.2,
    dividendYield: 5.2,
    industryDividendYieldAverage: 4.8,
    netProfitGrowth: 18.5,
    revenueGrowth: 12.3,
    industryNetProfitGrowthAverage: 12.8,
    industryRevenueGrowthAverage: 8.5,
    valuationTrend: 'stable',
    expectedGrowthYear1: 16,
    expectedGrowthYear2: 14,
    expectedGrowthYear3: 12,
    expectedRevenueGrowthYear1: 11,
    expectedRevenueGrowthYear2: 10,
    expectedRevenueGrowthYear3: 9
  }
];

// 随机选择指定数量的股票
function selectRandomStocks(count = 3) {
  const shuffled = [...stockDatabase].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export { selectRandomStocks, stockDatabase };
